### ISSUE TITLE
New user with roles based on "reference user"

### ISSUE THREAD

**Issue by niv0** [isisaddons/isis-module-security#30]
Would be great if new user can be created with same "role profile" as an existing "reference user".

**Comment by danhaywood** [comment]
Would "clone user" work as an approach?

**Comment by niv0** [comment]
Yes, I think it would lead to same result.

**Comment by danhaywood** [comment]
Would you be happy to implement this, then (with tests)?  Seems like quite a straight-forward enhancement.

**Comment by niv0** [comment]
Ok , I can try that! Will send you a pull request when finished.

**Comment by danhaywood** [comment]
Good stuff, look forward to it.  

I care more about a nice integration test than unit tests, you could add to https://github.com/isisaddons/isis-module-security/blob/master/integtests/src/test/java/org/isisaddons/module/security/integtests/user/ApplicationUserIntegTest.java (I used nested static classes as a way of organizing the testing of the responsibilities).

Cheers

**Comment by niv0** [comment]
Yes I saw that, I will introduce new nested static class as test.

**Comment by niv0** [comment]
Hi Dan, I created a pull request

https://github.com/isisaddons/isis-module-security/pull/33 

Regs,Vladimir

**Comment by danhaywood** [comment]
was closed by PR #33
