### ISSUE TITLE
Adding a package to a role doesn't work

### ISSUE THREAD

**Issue by martin-g** [isisaddons/isis-module-security#9]
While working on https://issues.apache.org/jira/browse/ISIS-1011 I've noticed that adding a new package to a role doesn't add it to it.

To reproduce:
- start isis-module-security webapp
- login with `isis-module-security-admin`
- open any role, e.g. `isis-module-security-admin`
- use `Add Package` to add a new package

After entering valid values the new package doesn't appear in the table with permissions.

**Comment by danhaywood** [comment]
I've just tried this, and can't reproduce... the new permission is created
at the package level.  Perhaps the issue was to do with that defect in
select2 (ISIS-1011) which you've now fixed?)

**Comment by martin-g** [comment]
No. The issue was/is there before and after ISIS-1011.
What exactly do you mean with "at the package level" ? Is that the table below the button "Add package" ?

**Comment by danhaywood** [comment]
The table below contains the permissions which are either for the package, or for the class, or for an individual member (property/collection/action).  Gonna close this ticket but feel free to open if there is genuinely an issue.
